In [1]:
import numpy as np
from scipy.linalg import eigh

# Function to generate a random symmetric matrix
def generate_symmetric_matrix(d):
    # Create random values from U[-1, 1] for upper triangular part
    mat = np.random.uniform(-1, 1, size=(d, d))
    
    # Make the matrix symmetric
    mat = np.triu(mat)
    mat += mat.T - np.diag(mat.diagonal())
    
    return mat

# Function to correct the matrix to be positive definite
def make_positive_definite(mat, epsilon=1e-6):
    # Eigen decomposition
    eigenvalues, eigenvectors = eigh(mat)
    
    # If the smallest eigenvalue is negative, shift all eigenvalues
    lambda_min = np.min(eigenvalues)
    if lambda_min <= 0:
        mat += np.eye(mat.shape[0]) * (-lambda_min + epsilon)
    
    return mat

# Function to convert a covariance matrix to a correlation matrix
def cov_to_corr(mat):
    d = np.sqrt(np.diag(mat))
    return mat / np.outer(d, d)

# Function to generate a valid correlation matrix
def generate_correlation_matrix(d):
    # Step 1: Generate a random symmetric matrix
    sym_mat = generate_symmetric_matrix(d)
    
    # Step 2: Make it positive definite
    pos_def_mat = make_positive_definite(sym_mat)
    
    # Step 3: Convert to a correlation matrix
    cor_mat = cov_to_corr(pos_def_mat)
    
    return cor_mat

# Generate three 3x3 correlation matrices
np.random.seed(42)  # Set seed for reproducibility
cor_matrix_1 = generate_correlation_matrix(3)
cor_matrix_2 = generate_correlation_matrix(3)
cor_matrix_3 = generate_correlation_matrix(3)

# Print the matrices
print("Correlation Matrix 1:\n", cor_matrix_1)
print("Correlation Matrix 2:\n", cor_matrix_2)
print("Correlation Matrix 3:\n", cor_matrix_3)


Correlation Matrix 1:
 [[ 1.          0.71531806  0.27147633]
 [ 0.71531806  1.         -0.47836256]
 [ 0.27147633 -0.47836256  1.        ]]
Correlation Matrix 2:
 [[ 1.         -0.99432444  0.67876556]
 [-0.99432444  1.         -0.75303379]
 [ 0.67876556 -0.75303379  1.        ]]
Correlation Matrix 3:
 [[ 1.         -0.82057695  0.60779367]
 [-0.82057695  1.         -0.95259169]
 [ 0.60779367 -0.95259169  1.        ]]
